insert into hotel_menu (id, customerName, dishName, price) values (1, 'Rahul', 'Theeyal', 434.36);
insert into hotel_menu (id, customerName, dishName, price) values (2, 'Sreedevi', 'Fish Curry', 318.45);
insert into hotel_menu (id, customerName, dishName, price) values (3, 'Sajith', 'Kappa Puzhukku', 122.28);
insert into hotel_menu (id, customerName, dishName, price) values (4, 'Arjun', 'Idli', 443.95);
insert into hotel_menu (id, customerName, dishName, price) values (5, 'Vinu', 'Beef Fry', 170.83);
insert into hotel_menu (id, customerName, dishName, price) values (6, 'Aswathy', 'Neyyappam', 83.73);
insert into hotel_menu (id, customerName, dishName, price) values (7, 'Arjun', 'Kanji', 84.73);
insert into hotel_menu (id, customerName, dishName, price) values (8, 'Deepak', 'Pazham Pori', 425.57);
insert into hotel_menu (id, customerName, dishName, price) values (9, 'Soman', 'Dosa', 296.61);
insert into hotel_menu (id, customerName, dishName, price) values (10, 'Binu', 'Sambar', 75.4);
insert into hotel_menu (id, customerName, dishName, price) values (11, 'Lekshmi', 'Kichadi', 252.37);
insert into hotel_menu (id, customerName, dishName, price) values (12, 'Neethu', 'Fish Fry', 185.05);
insert into hotel_menu (id, customerName, dishName, price) values (13, 'Arjun', 'Prawn Curry', 90.14);
insert into hotel_menu (id, customerName, dishName, price) values (14, 'Lekshmi', 'Kerala Sadya', 311.2);
insert into hotel_menu (id, customerName, dishName, price) values (15, 'Jyothi', 'Fish Curry', 176.91);
insert into hotel_menu (id, customerName, dishName, price) values (16, 'Jyothi', 'Kozhukkatta', 232.35);
insert into hotel_menu (id, customerName, dishName, price) values (17, 'Jyothi', 'Kichadi', 74.98);
insert into hotel_menu (id, customerName, dishName, price) values (18, 'Sanju', 'Kanji', 336.09);
insert into hotel_menu (id, customerName, dishName, price) values (19, 'Shaji', 'Karimeen Pollichathu', 479.23);
insert into hotel_menu (id, customerName, dishName, price) values (20, 'Swathi', 'Beef Fry', 130.81);
insert into hotel_menu (id, customerName, dishName, price) values (21, 'Sreedevi', 'Chicken Roast', 296.92);
insert into hotel_menu (id, customerName, dishName, price) values (22, 'Gopi', 'Unniyappam', 135.25);
insert into hotel_menu (id, customerName, dishName, price) values (23, 'Reena', 'Puttu', 160.68);
insert into hotel_menu (id, customerName, dishName, price) values (24, 'Sujith', 'Uppumanga Curry', 94.49);
insert into hotel_menu (id, customerName, dishName, price) values (25, 'Pradeep', 'Pazham Pori', 62.2);
insert into hotel_menu (id, customerName, dishName, price) values (26, 'Shilpa', 'Appam', 187.66);
insert into hotel_menu (id, customerName, dishName, price) values (27, 'Devika', 'Nadan Kozhi Curry', 451.47);
insert into hotel_menu (id, customerName, dishName, price) values (28, 'Swathi', 'Kichadi', 187.96);
insert into hotel_menu (id, customerName, dishName, price) values (29, 'Sandhya', 'Kerala Sadya', 447.03);
insert into hotel_menu (id, customerName, dishName, price) values (30, 'Priya', 'Meen Curry', 350.72);
insert into hotel_menu (id, customerName, dishName, price) values (31, 'Sandhya', 'Mutta Roast', 95.54);
insert into hotel_menu (id, customerName, dishName, price) values (32, 'Reena', 'Mutta Curry', 272.14);
insert into hotel_menu (id, customerName, dishName, price) values (33, 'Vinod', 'Chemmeen Curry', 107.32);
insert into hotel_menu (id, customerName, dishName, price) values (34, 'Rajesh', 'Neyyappam', 198.84);
insert into hotel_menu (id, customerName, dishName, price) values (35, 'Reena', 'Chicken Roast', 277.15);
insert into hotel_menu (id, customerName, dishName, price) values (36, 'Ranjith', 'Idiyappam', 461.33);
insert into hotel_menu (id, customerName, dishName, price) values (37, 'Kannan', 'Prawn Fry', 333.26);
insert into hotel_menu (id, customerName, dishName, price) values (38, 'Jayan', 'Meen Curry', 386.2);
insert into hotel_menu (id, customerName, dishName, price) values (39, 'Nisha', 'Kozhukkatta', 446.63);
insert into hotel_menu (id, customerName, dishName, price) values (40, 'Nisha', 'Erissery', 205.11);
insert into hotel_menu (id, customerName, dishName, price) values (41, 'Binu', 'Kerala Parotta', 51.85);
insert into hotel_menu (id, customerName, dishName, price) values (42, 'Unni', 'Pazham Nirachathu', 456.92);
insert into hotel_menu (id, customerName, dishName, price) values (43, 'Rahul', 'Kalan', 424.65);
insert into hotel_menu (id, customerName, dishName, price) values (44, 'Kannan', 'Pathiri', 192.71);
insert into hotel_menu (id, customerName, dishName, price) values (45, 'Sreekumar', 'Avial', 464.52);
insert into hotel_menu (id, customerName, dishName, price) values (46, 'Sunil', 'Kozhi Varuthathu', 445.94);
insert into hotel_menu (id, customerName, dishName, price) values (47, 'Meera', 'Ela Ada', 78.55);
insert into hotel_menu (id, customerName, dishName, price) values (48, 'Lekshmi', 'Avial', 102.13);
insert into hotel_menu (id, customerName, dishName, price) values (49, 'Neethu', 'Kerala Sadya', 168.13);
insert into hotel_menu (id, customerName, dishName, price) values (50, 'Yasmin', 'Kappa Fry', 400.64);
insert into hotel_menu (id, customerName, dishName, price) values (51, 'Sanju', 'Chutney', 463.88);
insert into hotel_menu (id, customerName, dishName, price) values (52, 'Sunil', 'Thoran', 174.36);
insert into hotel_menu (id, customerName, dishName, price) values (53, 'Shaji', 'Uppumanga Curry', 263.22);
insert into hotel_menu (id, customerName, dishName, price) values (54, 'Pradeep', 'Kozhi Varuthathu', 200.29);
insert into hotel_menu (id, customerName, dishName, price) values (55, 'Ranjith', 'Thalassery Biryani', 89.4);
insert into hotel_menu (id, customerName, dishName, price) values (56, 'Ranjith', 'Chutney', 196.18);
insert into hotel_menu (id, customerName, dishName, price) values (57, 'Swathi', 'Puttu', 332.42);
insert into hotel_menu (id, customerName, dishName, price) values (58, 'Ranjith', 'Chakka Varatti', 440.13);
insert into hotel_menu (id, customerName, dishName, price) values (59, 'Shilpa', 'Kanji', 174.6);
insert into hotel_menu (id, customerName, dishName, price) values (60, 'Sreekumar', 'Kichadi', 149.06);
insert into hotel_menu (id, customerName, dishName, price) values (61, 'Rajesh', 'Thoran', 412.71);
insert into hotel_menu (id, customerName, dishName, price) values (62, 'Jyothi', 'Nadan Kozhi Curry', 377.32);
insert into hotel_menu (id, customerName, dishName, price) values (63, 'Unni', 'Chicken Roast', 344.11);
insert into hotel_menu (id, customerName, dishName, price) values (64, 'Jayan', 'Kichadi', 216.48);
insert into hotel_menu (id, customerName, dishName, price) values (65, 'Priya', 'Chemmeen Curry', 284.41);
insert into hotel_menu (id, customerName, dishName, price) values (66, 'Surya', 'Kappa Puzhukku', 277.66);
insert into hotel_menu (id, customerName, dishName, price) values (67, 'Priya', 'Prawn Curry', 421.93);
insert into hotel_menu (id, customerName, dishName, price) values (68, 'Ranjith', 'Malabar Biryani', 437.5);
insert into hotel_menu (id, customerName, dishName, price) values (69, 'Hari', 'Nadan Kozhi Curry', 177.6);
insert into hotel_menu (id, customerName, dishName, price) values (70, 'Ranjith', 'Kerala Sadya', 496.56);
insert into hotel_menu (id, customerName, dishName, price) values (71, 'Hari', 'Kerala Parotta', 414.62);
insert into hotel_menu (id, customerName, dishName, price) values (72, 'Sajith', 'Prawn Fry', 193.41);
insert into hotel_menu (id, customerName, dishName, price) values (73, 'Aswathy', 'Beef Fry', 389.13);
insert into hotel_menu (id, customerName, dishName, price) values (74, 'Sasi', 'Unniyappam', 460.3);
insert into hotel_menu (id, customerName, dishName, price) values (75, 'Divya', 'Fish Fry', 95.93);
insert into hotel_menu (id, customerName, dishName, price) values (76, 'Akhil', 'Ela Ada', 161.15);
insert into hotel_menu (id, customerName, dishName, price) values (77, 'Swathi', 'Banana Chips', 98.72);
insert into hotel_menu (id, customerName, dishName, price) values (78, 'Soman', 'Kozhukkatta', 422.04);
insert into hotel_menu (id, customerName, dishName, price) values (79, 'Sajith', 'Beef Fry', 491.55);
insert into hotel_menu (id, customerName, dishName, price) values (80, 'Sajith', 'Pathiri', 283.24);
insert into hotel_menu (id, customerName, dishName, price) values (81, 'Hari', 'Fish Curry', 303.88);
insert into hotel_menu (id, customerName, dishName, price) values (82, 'Anjali', 'Pazham Nirachathu', 393.44);
insert into hotel_menu (id, customerName, dishName, price) values (83, 'Shaji', 'Kappa Puzhukku', 266.33);
insert into hotel_menu (id, customerName, dishName, price) values (84, 'Binu', 'Fish Moilee', 325.42);
insert into hotel_menu (id, customerName, dishName, price) values (85, 'Soman', 'Prawn Fry', 459.39);
insert into hotel_menu (id, customerName, dishName, price) values (86, 'Sasi', 'Erissery', 170.48);
insert into hotel_menu (id, customerName, dishName, price) values (87, 'Yasmin', 'Chutney', 234.16);
insert into hotel_menu (id, customerName, dishName, price) values (88, 'Aswathy', 'Chakka Varatti', 408.07);
insert into hotel_menu (id, customerName, dishName, price) values (89, 'Anjali', 'Parippu Curry', 418.11);
insert into hotel_menu (id, customerName, dishName, price) values (90, 'Aswathy', 'Idli', 474.55);
insert into hotel_menu (id, customerName, dishName, price) values (91, 'Haritha', 'Nadan Kozhi Curry', 442.87);
insert into hotel_menu (id, customerName, dishName, price) values (92, 'Jyothi', 'Pazham Nirachathu', 489.4);
insert into hotel_menu (id, customerName, dishName, price) values (93, 'Sandhya', 'Dosa', 486.68);
insert into hotel_menu (id, customerName, dishName, price) values (94, 'Nisha', 'Chutney', 335.33);
insert into hotel_menu (id, customerName, dishName, price) values (95, 'Arjun', 'Kappa Puzhukku', 233.43);
insert into hotel_menu (id, customerName, dishName, price) values (96, 'Divya', 'Pathiri', 451.71);
insert into hotel_menu (id, customerName, dishName, price) values (97, 'Jyothi', 'Avial', 420.91);
insert into hotel_menu (id, customerName, dishName, price) values (98, 'Vinod', 'Unniyappam', 110.46);
insert into hotel_menu (id, customerName, dishName, price) values (99, 'Mohan', 'Kanji', 304.69);
insert into hotel_menu (id, customerName, dishName, price) values (100, 'Yasmin', 'Kappa Puzhukku', 419.66);
